services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build: .
    container_name: rate_limiter_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis-data:
